SELECT INFO.TRAIN, INFO.SNAME, INFO.STOPNUM, ATIMET, DTIMET,HP,SP,HST,HSM,HSB,SST,SSB,  
(CASE WHEN HP  IS NULL THEN 0 ELSE 硬座   END) AS 硬座  ,
(CASE WHEN SP  IS NULL THEN 0 ELSE 软座   END) AS 软座  ,
(CASE WHEN HST IS NULL THEN 0 ELSE 硬卧上 END) AS 硬卧上,
(CASE WHEN HSM IS NULL THEN 0 ELSE 硬卧中 END) AS 硬卧中,
(CASE WHEN HSB IS NULL THEN 0 ELSE 硬卧下 END) AS 硬卧下,
(CASE WHEN SST IS NULL THEN 0 ELSE 软卧上 END) AS 软卧上,
(CASE WHEN SSB IS NULL THEN 0 ELSE 软卧下 END) AS 软卧下
FROM (SELECT    
    TRAIN   ,
    SNAME   ,
    STOPNUM ,
    concat(DATE_PART('hour',ATIME),':', DATE_PART('minute',ATIME))::TIME AS ATIMET,
    (CASE WHEN DTIME  IS NULL THEN NULL ELSE concat(DATE_PART('hour',DTIME),':', DATE_PART('minute',DTIME))::TIME END) AS DTIMET,
    HP      ,
    SP      ,
    HST     ,
    HSM     ,
    HSB     ,
    SST     ,
    SSB     
FROM TRAIN_STATION
WHERE TRAIN = $1
    AND ATIME IS NOT NULL)
AS INFO,
(SELECT STOPNUM, SNAME,
      MAX(CASE TICKETTYPE WHEN '硬座'   THEN TCOUNT ELSE 0 END) AS 硬座  ,
      MAX(CASE TICKETTYPE WHEN '软座'   THEN TCOUNT ELSE 0 END) AS 软座  ,
      MAX(CASE TICKETTYPE WHEN '硬卧上' THEN TCOUNT ELSE 0 END) AS 硬卧上,
      MAX(CASE TICKETTYPE WHEN '硬卧中' THEN TCOUNT ELSE 0 END) AS 硬卧中,
      MAX(CASE TICKETTYPE WHEN '硬卧下' THEN TCOUNT ELSE 0 END) AS 硬卧下,
      MAX(CASE TICKETTYPE WHEN '软卧上' THEN TCOUNT ELSE 0 END) AS 软卧上,
      MAX(CASE TICKETTYPE WHEN '软卧下' THEN TCOUNT ELSE 0 END) AS 软卧下
FROM(
SELECT STOPNUM, SNAME, TICKETTYPE, COUNT(*) AS TCOUNT
FROM TRAIN_STATION AS TS, SEAT
WHERE 
    	TS.TRAIN = $1
	AND SEATID NOT IN (
        SELECT SEATID
        FROM TCK_STOPNUM AS TCK
        WHERE 
                TICKET_DATE = $2
            AND TCK.TRAIN = TS.TRAIN
            AND (   /*T1为出发站点 T2为到达站点*/
                    (STOPNUM1 <= 1 AND 1 < STOPNUM1)
                    OR
                    (STOPNUM1 < TS.STOPNUM AND TS.STOPNUM <= STOPNUM2))
	)
GROUP BY STOPNUM,SNAME, TICKETTYPE
) AS RESULT
GROUP BY STOPNUM, SNAME
ORDER BY STOPNUM)
AS TICKETS
WHERE 
    INFO.STOPNUM = TICKETS.STOPNUM;